[project]
authors = ["Mattias de Hollander <m.dehollander@nioo.knaw.nl>"]
channels = ["conda-forge"]
name = "renovate-pixi-test"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.3,<3.14"
geographiclib = ">=2.0,<3"
geopy = ">=2.4.1,<3"
cartopy = ">=0.24.0,<0.25"
pydantic = ">=2.11.2,<3"
matplotlib = ">=3.10.1,<4"
pyqt = ">=5.15.9,<6"
pandas = ">=2.2.3,<3"
python-dateutil = ">=2.9.0.post0,<3"
rich = ">=14.0.0,<15"
scipy = ">=1.15.2,<2"
tqdm = ">=4.67.1,<5"
tzdata = ">=2025b,<2026a"
numpy = ">=2.2.4,<3"
adjusttext = ">=1.3.0,<2"
iris = ">=3.12.0,<4"
