[project]
authors = ["Mattias de Hollander <m.dehollander@nioo.knaw.nl>"]
channels = ["conda-forge"]
name = "renovate-pixi-test"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.7,<3.15"
geographiclib = ">=2.1,<3"
geopy = ">=2.5.0,<3"
cartopy = ">=0.25.0,<0.26"
pydantic = ">=2.13.5,<3"
matplotlib = ">=3.11.1,<4"
pyqt = ">=5.15.11,<6"
pandas = ">=3.0.5,<4"
python-dateutil = ">=2.9.0.post0,<3"
rich = ">=15.0.0,<16"
scipy = ">=1.18.0,<2"
tqdm = ">=4.70.0,<5"
tzdata = ">=2026c,<2027a"
numpy = ">=2.5.3,<3"
adjusttext = ">=1.4.0,<2"
iris = ">=3.16.0,<4"
