[project]
authors = ["Mattias de Hollander <m.dehollander@nioo.knaw.nl>"]
channels = ["conda-forge"]
name = "renovate-pixi-test"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.12.1,<3.13"
